services:
  db:
    image: postgres:13
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: FasTracks_BE_production

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Your custom Nginx config
    depends_on:
      - web
    networks:
      - web-network

  web:
    build: .
    command: bash -c "bundle install && bundle exec rails server -b 0.0.0.0"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}  # Environment variable for the master key
      DATABASE_URL: postgres://postgres:password@db/FasTracks_BE_production
    entrypoint: ["bash", "-c", "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"]

volumes:
  postgres-data:

networks:
  web-network:
    driver: bridge
